language: node_js
node_js: "12"
branches:
  only:
    - development
    - master
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
